name: Build and Deploy Go Application

# Trigger this workflow on push to the main branch.
on:
  push:
    release:
      branches: [ 'main' ]
      types: [ created ]

env:
  REGISTRY: ghcr.io

# Define the workflow jobs.
jobs:
  build:
    name: Build Docker Image
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code repository.
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment (matching Go version 1.23).
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      # Step 3: Authenticate with DockerHub (or other container registry).
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Get the tag to use for image
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          #            my-docker-hub-namespace/my-docker-hub-repository
          images: |
            ${{ env.REGISTRY }}/${{ github.repository }}

      # Step 5: Push the Docker image to the registry.
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}